[project]
name = "ai-image-optimizer-self"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "opencv-python>=4.13.0.90",
    "pillow>=12.1.0",
    "python-dotenv>=1.2.1",
]
